import Head from 'next/head';
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import Tickets from '@/components/Tickets';
import Lineup from '@/components/Lineup';
import Artists from '@/components/Artists';
import Info from '@/components/Info';
import Contact from '@/components/Contact';
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hullabalooza</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Hero/>
        <Tickets/>
        <Lineup/>
        <Artists/>
        <Info/>
        <Contact/>
        <Footer/>
      </main>
    </>
  )
}
